# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.



services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
        # pass this value to any $projectDir argument for any service
        # that's created in this file (including controller arguments)
        string $projectDir: '%kernel.project_dir%'
    
  
  FDS\MultiTenancyBundle\Service\TenantService:
    autowire: true
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
        # pass this value to any $projectDir argument for any service
        # that's created in this file (including controller arguments)
        string $tenantEntity: '%fds.tenant_entity%'

  FDS\MultiTenancyBundle\Service\ConfigurationGeneratorService:
    arguments:
      $container: '@service_container'

  FDS\MultiTenancyBundle\Command\CreateDbCommand:
  FDS\MultiTenancyBundle\Command\MigrateDbCommand:
  FDS\MultiTenancyBundle\Command\SeedsCommand:

    
  
            
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
